Exception on /payments/42 [GET]
Traceback (most recent call last):
  File "/home/barlach/.local/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/barlach/.local/lib/python3.8/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/barlach/.local/lib/python3.8/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/barlach/.local/lib/python3.8/site-packages/flask/app.py", line 1956, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
